framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    session:
        enabled: true
        handler_id: null
        cookie_secure: 'auto'
        cookie_samesite: lax

    # Activer les annotations
    annotations:
        enabled: true

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
