framework:
    messenger:
        failure_transport: failed

        transports:
            # Change async transport to sync transport
            sync: 'sync://'
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            Symfony\Component\Notifier\Message\ChatMessage: sync
            Symfony\Component\Notifier\Message\SmsMessage: sync
            # Example routing for your own messages
            # 'App\Message\YourMessage': sync
