security:
    # Configuration pour le hashing des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateurs
    providers:
        # Configuration du fournisseur basé sur l'entité `Utilisateur`
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur # Spécifie votre classe Utilisateur
                property: email # Identifiant principal (modifiez si nécessaire)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider # Associe le fournisseur au firewall principal
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
                # Optionnel : redirigez après la déconnexion
                # target: app_homepage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # Durée de vie du cookie (1 semaine)
                path: /
                # always_remember_me: true # Toujours activer le "remember me" si besoin

    # Contrôle d'accès (Access Control)
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN } # Accès à /admin limité aux administrateurs
        - { path: ^/profile, roles: ROLE_USER } # Accès à /profile limité aux utilisateurs connectés

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Bcrypt minimal pour les tests
                time_cost: 3 # Argon minimal pour les tests
                memory_cost: 10 # Argon minimal pour les tests
