security:
    # Disable all firewalls (no authentication)
    firewalls:
        dev:
            # Allow access without authentication in the dev environment
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # Allow access without authentication for the main firewall
            security: false
    
    # Disable access control rules (no restrictions)
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
