parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true      # Automatically inject dependencies
        autoconfigure: true # Automatically register your services as commands, event subscribers, etc.
        public: false       # Set the services to private by default
   
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
   
    
   
    App\Service\ProduitService:
        arguments:
            $produitRepository: '@App\Repository\ProduitRepository'
 
 

    # Define the CartController service and inject EntityManager explicitly
    App\Controller\CartController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['controller.service_arguments']

    # App controllers and other services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Define the CartService service
    App\Service\CartService:
        autowire: true

   
    

    