parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true      # Automatically inject dependencies
        autoconfigure: true # Automatically register your services as commands, event subscribers, etc.
        public: false       # Set the services to private by default

    # Example service definition for FileUploader service
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%images_directory%'

    # App controllers and other services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\CartService:
        autowire: true

